[package]
name = "ipset"
version = "0.4.0"
edition = "2021"
license = "MIT"
description = "A wrapper for libipset"
repository = "https://github.com/lazytiger/ipset"
links = "ipset"

[dependencies]
libc = "0.2"
derive_more = "0.99"
